use bevy::ecs::component::Component;

/// Marker components for Godot node types.
/// These enable type-safe ECS queries like: Query<&GodotNodeHandle, With<Sprite2DMarker>>
///
/// 🤖 This file is automatically generated by scripts/generate_godot_types.py
/// To regenerate: python scripts/generate_godot_types.py

// Base node type marker
#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct NodeMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct AcceptDialogMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct AnimatableBody2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct AnimatableBody3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct AnimatedSprite2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct AnimatedSprite3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct AnimationMixerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct AnimationPlayerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct AnimationTreeMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct Area2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct Area3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct AspectRatioContainerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct AudioListener2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct AudioListener3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct AudioStreamPlayerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct AudioStreamPlayer2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct AudioStreamPlayer3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct BackBufferCopyMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct BaseButtonMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct Bone2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct BoneAttachment3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct BoxContainerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct ButtonMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct CPUParticles2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct CPUParticles3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct CSGBox3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct CSGCombiner3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct CSGCylinder3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct CSGMesh3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct CSGPolygon3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct CSGPrimitive3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct CSGShape3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct CSGSphere3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct CSGTorus3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct Camera2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct Camera3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct CanvasGroupMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct CanvasItemMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct CanvasLayerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct CanvasModulateMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct CenterContainerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct CharacterBody2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct CharacterBody3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct CheckBoxMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct CheckButtonMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct CodeEditMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct CollisionObject2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct CollisionObject3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct CollisionPolygon2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct CollisionPolygon3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct CollisionShape2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct CollisionShape3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct ColorPickerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct ColorPickerButtonMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct ColorRectMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct ConeTwistJoint3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct ConfirmationDialogMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct ContainerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct ControlMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct DampedSpringJoint2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct DecalMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct DirectionalLight2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct DirectionalLight3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct FileDialogMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct FileSystemDockMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct FlowContainerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct FogVolumeMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct GPUParticles2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct GPUParticles3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct GPUParticlesAttractor3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct GPUParticlesAttractorBox3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct GPUParticlesAttractorSphere3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct GPUParticlesAttractorVectorField3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct GPUParticlesCollision3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct GPUParticlesCollisionBox3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct GPUParticlesCollisionHeightField3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct GPUParticlesCollisionSDF3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct GPUParticlesCollisionSphere3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct Generic6DOFJoint3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct GeometryInstance3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct GraphEditMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct GraphElementMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct GraphFrameMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct GraphNodeMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct GridContainerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct GridMapMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct GridMapEditorPluginMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct GrooveJoint2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct HBoxContainerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct HFlowContainerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct HScrollBarMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct HSeparatorMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct HSliderMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct HSplitContainerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct HTTPRequestMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct HingeJoint3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct InstancePlaceholderMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct ItemListMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct Joint2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct Joint3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct LabelMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct Label3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct Light2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct Light3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct LightOccluder2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct LightmapGIMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct LightmapProbeMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct Line2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct LineEditMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct LinkButtonMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct LookAtModifier3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct MarginContainerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct Marker2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct Marker3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct MenuBarMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct MenuButtonMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct MeshInstance2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct MeshInstance3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct MultiMeshInstance2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct MultiMeshInstance3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct MultiplayerSpawnerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct MultiplayerSynchronizerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct NavigationAgent2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct NavigationAgent3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct NavigationLink2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct NavigationLink3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct NavigationObstacle2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct NavigationObstacle3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct NavigationRegion2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct NavigationRegion3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct NinePatchRectMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct Node2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct Node3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct OccluderInstance3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct OmniLight3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct OpenXRBindingModifierEditorMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct OpenXRCompositionLayerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct OpenXRCompositionLayerCylinderMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct OpenXRCompositionLayerEquirectMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct OpenXRCompositionLayerQuadMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct OpenXRHandMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct OpenXRInteractionProfileEditorMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct OpenXRInteractionProfileEditorBaseMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct OpenXRVisibilityMaskMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct OptionButtonMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct PanelMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct PanelContainerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct Parallax2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct ParallaxBackgroundMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct ParallaxLayerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct Path2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct Path3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct PathFollow2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct PathFollow3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct PhysicalBone2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct PhysicalBone3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct PhysicalBoneSimulator3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct PhysicsBody2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct PhysicsBody3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct PinJoint2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct PinJoint3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct PointLight2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct Polygon2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct PopupMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct PopupMenuMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct PopupPanelMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct ProgressBarMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct RangeMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct RayCast2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct RayCast3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct ReferenceRectMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct ReflectionProbeMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct RemoteTransform2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct RemoteTransform3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct ResourcePreloaderMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct RetargetModifier3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct RichTextLabelMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct RigidBody2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct RigidBody3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct RootMotionViewMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct ScriptCreateDialogMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct ScrollBarMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct ScrollContainerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct SeparatorMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct ShaderGlobalsOverrideMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct ShapeCast2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct ShapeCast3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct Skeleton2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct Skeleton3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct SkeletonIK3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct SkeletonModifier3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct SliderMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct SliderJoint3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct SoftBody3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct SpinBoxMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct SplitContainerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct SpotLight3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct SpringArm3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct SpringBoneCollision3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct SpringBoneCollisionCapsule3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct SpringBoneCollisionPlane3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct SpringBoneCollisionSphere3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct SpringBoneSimulator3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct Sprite2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct Sprite3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct SpriteBase3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct StaticBody2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct StaticBody3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct StatusIndicatorMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct SubViewportMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct SubViewportContainerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct TabBarMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct TabContainerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct TextEditMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct TextureButtonMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct TextureProgressBarMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct TextureRectMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct TileMapMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct TileMapLayerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct TimerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct TouchScreenButtonMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct TreeMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct VBoxContainerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct VFlowContainerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct VScrollBarMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct VSeparatorMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct VSliderMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct VSplitContainerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct VehicleBody3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct VehicleWheel3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct VideoStreamPlayerMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct ViewportMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct VisibleOnScreenEnabler2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct VisibleOnScreenEnabler3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct VisibleOnScreenNotifier2DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct VisibleOnScreenNotifier3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct VisualInstance3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct VoxelGIMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct WindowMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct WorldEnvironmentMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct XRAnchor3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct XRBodyModifier3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct XRCamera3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct XRController3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct XRFaceModifier3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct XRHandModifier3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct XRNode3DMarker;

#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct XROrigin3DMarker;
