pub use crate::GodotPlugin;
pub use crate::autosync::AutoSyncBundleRegistry;
pub use crate::bridge::*;
pub use crate::node_tree_view::NodeTreeView;
#[allow(deprecated)]
pub use crate::plugins::{
    assets::{GodotAssetsPlugin, GodotResource},
    audio::{
        Audio, AudioApp, AudioChannel, AudioChannelMarker, AudioEasing, AudioError, AudioOutput,
        AudioPlayerType, AudioSettings, AudioTween, GodotAudioChannels, GodotAudioPlugin,
        MainAudioTrack, PlayAudioCommand, SoundId,
    },
    core::{
        ActionInput,
        // Node type marker components for type-safe ECS queries
        AnimatedSprite2DMarker,
        AnimatedSprite3DMarker,
        AnimationPlayerMarker,
        AnimationTreeMarker,
        Area2DMarker,
        Area3DMarker,
        AudioStreamPlayer2DMarker,
        AudioStreamPlayer3DMarker,
        AudioStreamPlayerMarker,
        BevyInputBridgePlugin,
        ButtonMarker,
        Camera2DMarker,
        Camera3DMarker,
        CanvasItemMarker,
        CharacterBody2DMarker,
        CharacterBody3DMarker,
        CollisionPolygon2DMarker,
        CollisionPolygon3DMarker,
        CollisionShape2DMarker,
        CollisionShape3DMarker,
        Collisions,
        ControlMarker,
        DirectionalLight3DMarker,
        FindEntityByNameExt,
        GodotCorePlugin,
        GodotSignal,
        GodotSignalArgument,
        GodotSignals,
        GodotTransformConfig,
        Groups,
        KeyboardInput,
        LabelMarker,
        LineEditMarker,
        MeshInstance2DMarker,
        MeshInstance3DMarker,
        MouseButtonInput,
        MouseMotion,
        Node2DMarker,
        Node3DMarker,
        NodeMarker,
        PanelMarker,
        Path2DMarker,
        Path3DMarker,
        PathFollow2DMarker,
        PathFollow3DMarker,
        PhysicsDelta,
        PhysicsUpdate,
        RigidBody2DMarker,
        RigidBody3DMarker,
        SceneTreeEventReader,
        SceneTreeRef,
        SpotLight3DMarker,
        Sprite2DMarker,
        Sprite3DMarker,
        StaticBody2DMarker,
        StaticBody3DMarker,
        SystemDeltaTimer,
        TextEditMarker,
        TimerMarker,
        Transform2D,
        Transform3D,
        TransformSyncMode,
        collisions::{
            ALL_COLLISION_SIGNALS, AREA_ENTERED, AREA_EXITED, BODY_ENTERED, BODY_EXITED,
            COLLISION_END_SIGNALS, COLLISION_START_SIGNALS,
        },
        connect_godot_signal,
    },
    packed_scene::{GodotScene, PackedScenePlugin},
};
pub use godot::prelude as godot_prelude;
pub use godot_bevy_macros::*;
